<!doctype html><html lang="id"><head><meta charset="utf-8"><style>
@page{margin:20px}body{font-family:Arial,sans-serif;font-size:8px;color:#000}table{width:100%;border-collapse:collapse}.b{border:1px solid #000}.green{background:#e2efda}.c{text-align:center;vertical-align:middle}.l{vertical-align:top}.title{font-size:13px;font-weight:bold}.small{font-size:8px}.pad td{padding:3px;vertical-align:top}.items th,.items td{border:1px solid #000;padding:2px}.items th{background:#e2efda;text-align:center;vertical-align:middle}.items td{height:14px}.sign td{text-align:center;height:75px;vertical-align:bottom}.muted{color:#666}
</style></head><body>
<table class="b"><tr><td colspan="11" class="title" style="height:22px">II. &nbsp;&nbsp;&nbsp; LAPORAN FISIK MINGGUAN</td></tr>
<tr class="green"><td colspan="6" style="height:55px;padding:5px"><b>PEMERINTAH KABUPATEN KEDIRI</b><br>DINAS LINGKUNGAN HIDUP<br><b>{{ $summary['nama_proyek'] }}</b><br>{{ $summary['lokasi'] }}</td><td colspan="2" style="padding:5px"><b>MINGGU :</b> {{ $summary['minggu_ke'] }}<br><b>PERIODE :</b><br>{{ $summary['tanggal_mulai']->locale('id')->isoFormat('D MMMM Y') }} s/d<br>{{ $summary['tanggal_selesai']->locale('id')->isoFormat('D MMMM Y') }}</td><td colspan="3" class="c" style="padding:5px"><b>KONTRAKTOR / KONTRAKTOR PELAKSANA</b><br><br>{{ $summary['kontraktor'] ?: '-' }}</td></tr>
<tr><td colspan="11" class="pad" style="height:48px"><table style="width:100%; border:none; margin:0; padding:0;"><tr><td style="width:110px; font-weight:bold; border:none;">KEGIATAN</td><td style="width:10px; font-weight:bold; border:none;">:</td><td style="border:none;">{{ $summary['kegiatan'] }}</td></tr><tr><td style="font-weight:bold; border:none;">SUB KEGIATAN</td><td style="font-weight:bold; border:none;">:</td><td style="border:none;">{{ $summary['sub_kegiatan'] ?: '-' }}</td></tr><tr><td style="font-weight:bold; border:none;">PEKERJAAN</td><td style="font-weight:bold; border:none;">:</td><td style="border:none;">{{ $summary['pekerjaan'] }}</td></tr><tr><td style="font-weight:bold; border:none;">LOKASI</td><td style="font-weight:bold; border:none;">:</td><td style="border:none;">{{ $summary['lokasi'] }}</td></tr><tr><td style="font-weight:bold; border:none;">TAHUN ANGGARAN</td><td style="font-weight:bold; border:none;">:</td><td style="border:none;">{{ $summary['tahun_anggaran'] }}</td></tr></table></td></tr></table><br>
<table class="items"><thead><tr><th rowspan="3" style="width:3%">NO</th><th rowspan="3" style="width:29%">ITEM PEKERJAAN</th><th rowspan="3">VOLUME</th><th rowspan="3">SAT</th><th rowspan="3">BOBOT (%)</th><th colspan="6">PRESTASI PEKERJAAN</th></tr><tr><th colspan="2">S/D MINGGU LALU</th><th colspan="2">MINGGU INI</th><th colspan="2">S/D MINGGU INI</th></tr><tr><th>VOLUME</th><th>BOBOT (%)</th><th>VOLUME</th><th>BOBOT (%)</th><th>VOLUME</th><th>BOBOT (%)</th></tr></thead><tbody>
@forelse($rows as $row)
@if(!empty($row['is_header']))
<tr><td style="text-align: left; padding-left: 5px;"><b>{{ $row['no'] }}</b></td><td><b>{{ $row['item'] }}</b></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
@else
<tr><td style="text-align: right; padding-right: 5px;">{{ $row['no'] }}</td><td>{{ $row['item'] }}</td><td class="c">{{ $row['volume'] ?? '-' }}</td><td class="c">{{ $row['sat'] ?? '-' }}</td><td class="c">{{ number_format($row['bobot'] * 100, 3) }}%</td><td class="c">{{ $row['lalu_volume'] ?? '-' }}</td><td class="c">{{ number_format($row['lalu_bobot'] * 100, 3) }}%</td><td class="c">{{ $row['ini_volume'] ?? '-' }}</td><td class="c">{{ number_format($row['ini_bobot'] * 100, 3) }}%</td><td class="c">{{ $row['sampai_volume'] ?? '-' }}</td><td class="c">{{ number_format($row['sampai_bobot'] * 100, 3) }}%</td></tr>
@endif
@empty<tr><td colspan="11" class="c">Belum ada item pekerjaan</td></tr>@endforelse
<tr class="green"><td colspan="4"></td><td class="c"><b>100.000%</b></td><td colspan="2" class="c">0.000%</td><td colspan="2" class="c">{{ number_format($rows->sum('ini_bobot') * 100, 3) }}%</td><td colspan="2" class="c">{{ number_format($rows->sum('sampai_bobot') * 100, 3) }}%</td></tr></tbody></table><br>
<table class="sign"><tr><td colspan="3">Mengetahui:<br><b>PEJABAT PEMBUAT KOMITMEN</b><br>DINAS LINGKUNGAN HIDUP<br>KABUPATEN KEDIRI<br><br><br><b><u>WENI ARTANTI, ST. MH</u></b><br>NIP. 19810318 200902 2 004</td><td colspan="4">Diperiksa dan Diperiksa oleh:<br><b>KONSULTAN PENGAWAS</b><br><b>{{ $summary['konsultan'] ?: '-' }}</b><br><br><br><b><u>NIKOLAUS ADI KURNIA PUTRA</u></b><br>Direktur</td><td colspan="4">{{ $summary['tanggal_selesai']->locale('id')->isoFormat('D MMMM Y') }}<br><b>Kontraktor Pelaksana</b><br><b>{{ $summary['kontraktor'] ?: '-' }}</b><br><br><br><b><u>{{ $summary['pic'] ?: '________________________' }}</u></b><br>Pelaksana</td></tr></table>
</body></html>
