<table class="b"><tr><td colspan="11" class="title" style="height:22px">II. &nbsp;&nbsp;&nbsp; LAPORAN FISIK MINGGUAN</td></tr>
<tr class="green"><td colspan="6" style="height:55px;padding:5px"><b>PEMERINTAH KABUPATEN KEDIRI</b><br>DINAS LINGKUNGAN HIDUP<br><b><?php echo e($summary['nama_proyek']); ?></b><br><?php echo e($summary['lokasi']); ?></td><td colspan="2" style="padding:5px"><b>MINGGU :</b> <?php echo e($summary['minggu_ke']); ?><br><b>PERIODE :</b><br><?php echo e($summary['tanggal_mulai']->locale('id')->isoFormat('D MMMM Y')); ?> s/d<br><?php echo e($summary['tanggal_selesai']->locale('id')->isoFormat('D MMMM Y')); ?></td><td colspan="3" class="c" style="padding:5px"><b>KONTRAKTOR / KONTRAKTOR PELAKSANA</b><br><br><?php echo e($summary['kontraktor'] ?: '-'); ?></td></tr>
<tr><td colspan="11" class="pad" style="height:48px"><table style="width:100%; border:none; margin:0; padding:0;"><tr><td style="width:110px; font-weight:bold; border:none;">KEGIATAN</td><td style="width:10px; font-weight:bold; border:none;">:</td><td style="border:none;"><?php echo e($summary['kegiatan']); ?></td></tr><tr><td style="font-weight:bold; border:none;">SUB KEGIATAN</td><td style="font-weight:bold; border:none;">:</td><td style="border:none;"><?php echo e($summary['sub_kegiatan'] ?: '-'); ?></td></tr><tr><td style="font-weight:bold; border:none;">PEKERJAAN</td><td style="font-weight:bold; border:none;">:</td><td style="border:none;"><?php echo e($summary['pekerjaan']); ?></td></tr><tr><td style="font-weight:bold; border:none;">LOKASI</td><td style="font-weight:bold; border:none;">:</td><td style="border:none;"><?php echo e($summary['lokasi']); ?></td></tr><tr><td style="font-weight:bold; border:none;">TAHUN ANGGARAN</td><td style="font-weight:bold; border:none;">:</td><td style="border:none;"><?php echo e($summary['tahun_anggaran']); ?></td></tr></table></td></tr></table><br>
<table class="items"><thead><tr><th rowspan="3" style="width:3%">NO</th><th rowspan="3" style="width:29%">ITEM PEKERJAAN</th><th rowspan="3">VOLUME</th><th rowspan="3">SAT</th><th rowspan="3">BOBOT (%)</th><th colspan="6">PRESTASI PEKERJAAN</th></tr><tr><th colspan="2">S/D MINGGU LALU</th><th colspan="2">MINGGU INI</th><th colspan="2">S/D MINGGU INI</th></tr><tr><th>VOLUME</th><th>BOBOT (%)</th><th>VOLUME</th><th>BOBOT (%)</th><th>VOLUME</th><th>BOBOT (%)</th></tr></thead><tbody>
<?php $__empty_1 = true; $__currentLoopData = $rows; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $row): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
<?php if(!empty($row['is_header'])): ?>
<tr><td style="text-align: left; padding-left: 5px;"><b><?php echo e($row['no']); ?></b></td><td><b><?php echo e($row['item']); ?></b></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
<?php else: ?>
<tr><td style="text-align: right; padding-right: 5px;"><?php echo e($row['no']); ?></td><td><?php echo e($row['item']); ?></td><td class="c"><?php echo e($row['volume'] ?? '-'); ?></td><td class="c"><?php echo e($row['sat'] ?? '-'); ?></td><td class="c"><?php echo e(number_format($row['bobot'] * 100, 3)); ?>%</td><td class="c"><?php echo e($row['lalu_volume'] ?? '-'); ?></td><td class="c"><?php echo e(number_format($row['lalu_bobot'] * 100, 3)); ?>%</td><td class="c"><?php echo e($row['ini_volume'] ?? '-'); ?></td><td class="c"><?php echo e(number_format($row['ini_bobot'] * 100, 3)); ?>%</td><td class="c"><?php echo e($row['sampai_volume'] ?? '-'); ?></td><td class="c"><?php echo e(number_format($row['sampai_bobot'] * 100, 3)); ?>%</td></tr>
<?php endif; ?>
<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="11" class="c">Belum ada item pekerjaan</td></tr><?php endif; ?>
<tr class="green"><td colspan="4"></td><td class="c"><b>100.000%</b></td><td colspan="2" class="c">0.000%</td><td colspan="2" class="c"><?php echo e(number_format($rows->sum('ini_bobot') * 100, 3)); ?>%</td><td colspan="2" class="c"><?php echo e(number_format($rows->sum('sampai_bobot') * 100, 3)); ?>%</td></tr></tbody></table><br>
<table class="sign"><tr><td colspan="3">Mengetahui:<br><b>PEJABAT PEMBUAT KOMITMEN</b><br>DINAS LINGKUNGAN HIDUP<br>KABUPATEN KEDIRI<br><br><br><b><u>WENI ARTANTI, ST. MH</u></b><br>NIP. 19810318 200902 2 004</td><td colspan="4">Diperiksa dan Diperiksa oleh:<br><b>KONSULTAN PENGAWAS</b><br><b><?php echo e($summary['konsultan'] ?: '-'); ?></b><br><br><br><b><u>NIKOLAUS ADI KURNIA PUTRA</u></b><br>Direktur</td><td colspan="4">Kediri, <?php echo e($summary['tanggal_selesai']->locale('id')->isoFormat('D MMMM Y')); ?><br><b>Kontraktor Pelaksana</b><br><b><?php echo e($summary['kontraktor'] ?: '-'); ?></b><br><br><br><b><u><?php echo e($summary['pic'] ?: '________________________'); ?></u></b><br>Pelaksana</td></tr></table>
<?php /**PATH C:\PROJECT FANY\Bot-Monitoring-Pekerjaan\resources\views/pdf/weekly-physical-content.blade.php ENDPATH**/ ?>